function init(self)

end

function on_message(self, message_id, message, sender)
   if message_id == hash("solution") then
   		label.set_text("#V_Text", message[1])
   		print("SOLUTION RECIEVED")
   		msg.post("/game/Board/Board#script", "solHolder", {go.get_id()}) -- sends position of solution holder
   end
end

function on_input(self, action_id, action)
    -- Add input-handling code here
    -- Remove this function if not needed
end
